### ISSUE TITLE
Cursor and selection text are invisible 

### ISSUE THREAD

**Issue by george-151** [hltj/wxMEdit#148] opened 2016-08-17 15:34 UTC
Hi

Recently, I have made a fresh install of Ubuntu 16.04LTS- amd64 on my PC.
Unfortunately, the Cursor and selection text are invisible in the Text editor.

Best Regards
George

![screenshot](https://cloud.githubusercontent.com/assets/21083766/17742465/cad7554a-64a8-11e6-9541-b77df54644f4.png)

Copy button is enable but selection text is invisible.

**Comment by clys** [comment] 2016-12-13 02:55
Deepin 4.4.30 Also have this problem

**Comment by hltj** [comment] 2018-02-26 08:31
Sorry. This may be a historical bug under particular hareware/system environment. But I can't reproduce it and I don't how to get the environment to reproduce and test the problem.

**Comment by hltj** [comment] 2018-03-09 08:39
I have enabled the existing & commented out code (‘FIXINVERT’). It should fix this issue.
If it was not fixed with the newest code, please reopen this issue.

**Closed by hltj** 2018-03-09 08:39 UTC
