### ISSUE TITLE
Umlauts don't work, despite correct keyboard layout

### ISSUE THREAD

**Issue by MrColdbird** [hltj/wxMEdit#134] opened 2016-02-10 12:36 UTC
Can't type any umlauts like ä, ö, ü, ß.
Typing them in another application and copy-pasting them into wxMEdit works though.

Also, the mentioned keyboard keys can't be mapped in the Options either, which makes me believe that its an issue somewhere further down the input chain.

Issue is unlikely to be wxgtk related, as the older 3.0.2 source builds fine with the same wxgtk release and doesn't have the issue, suggesting it was introduced somewhere between the 3.0.2 release tag and now.

Haven't had the time to bisect the repository yet to pin-point the exact breaking commit.

**Comment by hltj** [comment] 2016-02-10 13:00
OK. I can location it by bisect. While, I can't reproduce the problem without the relative environment.
Could you tell me your OS & version (e.g. Debian Unstable), wxGTK release and your keyboard layout?

**Comment by hltj** [comment] 2016-02-10 13:01
And I'm not quite understand this:
> Also, the mentioned keyboard keys can't be mapped in the Options 
Could you take a example?

**Comment by MrColdbird** [comment] 2016-02-10 13:04
I'm running Arch Linux, my Keyboard Layout is de (latin, no-dead-keys), and the wxGTK release is 2.8.

About your mapping question, wxMEdit supports a custom key-mapping, you find it under Tools -> Options -> Keys, and the only reason I mentioned is because the broken keys aren't detected there either.

**Comment by hltj** [comment] 2016-02-10 13:06
OK. Got it. I will deal with it.

**Comment by hltj** [comment] 2016-02-11 15:12
It seems fixed by last commit 982f560.

While these keys cannot be mapped is another bug, and it maybe cannot fixed since it may be the bug of wxGTK. I will confirm it after 3.1 released.

**Comment by MrColdbird** [comment] 2016-02-11 16:21
Just did a rebuild and can confirm that I can now type umlauts.
The button mapping issue does remain however, as you said.

**Closed** 2016-02-12 01:33 UTC
Labels: bug
